spring.application.name=VeA_IZI_VSRC
spring.mvc.format.date=yyyy-MM-dd

# MYSQL settings / GVistins
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/vea_vsrc_izi
spring.datasource.username=user_spring
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name =com.mysql.cj.jdbc.Driver